WITH RECURSIVE CTE AS
    (SELECT 0 AS N
    UNION ALL
    SELECT N + 1 FROM CTE
    WHERE N < 23)

SELECT CTE.N AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM CTE LEFT JOIN ANIMAL_OUTS A
ON CTE.N = HOUR(A.DATETIME)
GROUP BY CTE.N
ORDER BY CTE.N
;